import { getApplyDetail } from './api';
import { IDetail } from './interface';

export const initDetail = {
  applyId: 0,
  applyTag: 0,
  leadsId: 0,
  remark: '',
  status: 0,
  creator: '',
  createTime: '',
  approvalRecordId: '',
  brandChineseName: '',
  brandEnglishName: '',
  brandCountry: '',
  mainCategory: '',
  mainCategoryId: 0,
  brandName: '',
  brandLogo: { key: '', url: '' },
  trademarkList: [],
  brandLayerSelfEvaluation: undefined,
  brandPriority: undefined,
  countryFlag: undefined,
  brandCountryFlag: 0,
  brandAlias: '',
  brandStory: '',
  oneProductMultiMerchant: 0,
  brandClasses: '',
  brandStyle: '',
  enterpriseName: '',
  price: 0,
  brandType: 0,
  brandTag: '',
  qualificationType: 0,
  isNewBrand: 0,
  brandValueDesc: '',
  supplyMode: 0,
  dailyPriceIndex: '',
  pricePromotionIndex: '',
  estimatePriceArriveTime: 0,
  spuNum: 0,
  monthlySales: undefined,
  estimateSaleArriveTime: 0,
  rate: '',
  fixedCost: 0,
  internetSaleInfos: [],
  brandHotInfoList: [],
  communitySeedingNum: undefined,
  layGoodsPercent: '',
  isSocialMediaDiversion: undefined,
  insideBudgetAmountPercent: '',
  gravityBudgetAmount: undefined,
  outsideBudgetAmount: undefined,
  outsideBudgetAmountPercent: '',
  dewuPostsNum: undefined,
  xiaohongshuPostsNum: undefined,
  tiktokVideoNum: undefined,
  tiktokVideoLikeNum: undefined,
  isLuxury: undefined,
  luxuryStyle: undefined,
  luxuryReason: '',
  taoDataGmv: undefined,
  offlineStoreAmount: undefined,
  annualSaleScale: undefined,
  monthlySaleAmount: undefined,
  tianMaoFans: undefined,
  weiboFans: undefined,
  tiktokFans: undefined,
  brandId: 0,
  serviceRate: '',
  reportStartTime: '',
  reportEndTime: '',
};

export const getDetail = async (
  applyId: number,
  setDetailInfo: React.Dispatch<IDetail>,
  bkStatus?: number,
) => {
  const data = await getApplyDetail({
    applyId,
  });
  const res = {
    applyId: data.applyId,
    applyTag: data.applyTag,
    leadsId: data.leadsId,
    remark: data.remark,
    status: data.status || bkStatus || 0,
    creator: data.creator,
    createTime: data.createTime,
    approvalRecordId: data.approvalRecordId,
    mainCategory: data.mainCategory,
    mainCategoryId: {
      value: data.mainCategoryId,
      label: data.mainCategory,
    },
    brandName: data.brandName,
    brandChineseName: data.brandChineseName,
    brandEnglishName: data.brandEnglishName,

    brandLayerSelfEvaluation: data.brandLayerSelfEvaluation,
    brandPriority: data.brandPriority,
    countryFlag: data.countryFlag,
    brandCountryFlag: data.brandCountryFlag,
    brandCountry: data.brandCountry,
    brandAlias: data.brandAlias,
    brandStory: data.brandStory,
    oneProductMultiMerchant: data.oneProductMultiMerchant,
    brandClasses: data.brandClasses,
    brandStyle: data.brandStyle,

    enterpriseName: data.enterpriseName,
    price: data.price,
    brandType: data.brandType,
    brandTag: data.brandTag,
    qualificationType: data.qualificationType,
    isNewBrand: data.isNewBrand,
    brandValueDesc: data.brandValueDesc,
    supplyMode: data.supplyMode,
    dailyPriceIndex: data.dailyPriceIndex,
    pricePromotionIndex: data.pricePromotionIndex,
    estimatePriceArriveTime: data.estimatePriceArriveTime,
    spuNum: data.spuNum,
    monthlySales: data.monthlySales,
    estimateSaleArriveTime: data.estimateSaleArriveTime,
    rate: data.serviceRate,
    fixedCost: data.fixedCost,
    internetSaleInfos: data.internetSaleInfos || [],
    brandHotInfoList: data.brandHotInfoList || [],
    communitySeedingNum: data.communitySeedingNum,
    layGoodsPercent: data.layGoodsPercent,
    isSocialMediaDiversion: data.isSocialMediaDiversion,
    insideBudgetAmountPercent: data.insideBudgetAmountPercent,
    gravityBudgetAmount: data.gravityBudgetAmount,
    outsideBudgetAmount: data.outsideBudgetAmount,
    outsideBudgetAmountPercent: data.outsideBudgetAmountPercent,
    dewuPostsNum: data.dewuPostsNum,
    xiaohongshuPostsNum: data.xiaohongshuPostsNum,
    tiktokVideoNum: data.tiktokVideoNum,
    tiktokVideoLikeNum: data.tiktokVideoLikeNum,
    isLuxury: data.isLuxury,
    luxuryStyle: data.luxuryStyle,
    luxuryReason: data.luxuryReason,
    taoDataGmv: data.taoDataGmv,
    brandLogo: data.brandLogo,
    offlineStoreAmount: data.offlineStoreAmount,
    annualSaleScale: data.annualSaleScale,
    monthlySaleAmount: data.monthlySaleAmount,
    tianMaoFans: data.tianMaoFans,
    weiboFans: data.weiboFans,
    tiktokFans: data.tiktokFans,
    // 5.23修改新增
    brandRightSubject: data?.brandRightSubject,
    trademarkList: data?.trademarkList || [],
    registerStatus: data?.registerStatus,
    trademarkStartTime: data?.trademarkStartTime,
    trademarkEndTime: data?.trademarkEndTime,
    commitmentProofList: data?.commitmentProofList || [],
    relationshipProofList: data?.relationshipProofList || [],
    foreignTrademarkList: data?.foreignTrademarkList || [],
    foreignRegisterStatus: data?.foreignRegisterStatus,
    foreignTrademarkStartTime: data?.foreignTrademarkStartTime,
    foreignTrademarkEndTime: data?.foreignTrademarkEndTime,
    foreignCommitmentProofList: data?.foreignCommitmentProofList || [],
    foreignRelationshipProofList: data?.foreignRelationshipProofList || [],
    layerRuleList: data?.layerRuleList || [],
  };
  setDetailInfo(res);
};
