// 没有使用mooncake是因为脱离耦合，让业务发开人员删除mock数据就可以立即使用。
// 虽然定义和api.ts里是重复的，但不要在代码中混用，mock.ts是完全独立的。

export const getProvince = function () {
  return [
    {
      id: 46918,
      areaIdentifier: 'NX',
      chineseAbbreviation: '宁夏',
      areaCode: '640000',
      regionalPinyin: 'NXHZZZQ',
      regionFullChineseName: 'NingXiaHuiZuZiZhiQu',
      areaName: '宁夏回族自治区',
      upperAreaCode: '1',
      pinYin: 'NingXia',
      areaType: 2,
    },
    {
      id: 47306,
      areaIdentifier: 'NM',
      chineseAbbreviation: '内蒙古',
      areaCode: '150000',
      regionalPinyin: 'NMGZZQ',
      regionFullChineseName: 'NeiMengGuZiZhiQu',
      areaName: '内蒙古自治区',
      upperAreaCode: '1',
      pinYin: 'NeiMengGu',
      areaType: 2,
    },
    {
      id: 48239,
      areaIdentifier: 'TJ',
      chineseAbbreviation: '天津',
      areaCode: '120000',
      regionalPinyin: 'TJS',
      regionFullChineseName: 'TianJinShi',
      areaName: '天津',
      upperAreaCode: '1',
      pinYin: 'TianJin',
      areaType: 2,
    },
    {
      id: 49638,
      areaIdentifier: 'LN',
      chineseAbbreviation: '辽宁',
      areaCode: '210000',
      regionalPinyin: 'LNS',
      regionFullChineseName: 'LiaoNingSheng',
      areaName: '辽宁省',
      upperAreaCode: '1',
      pinYin: 'LiaoNing',
      areaType: 2,
    },
    {
      id: 50758,
      areaIdentifier: 'HK',
      chineseAbbreviation: '香港',
      areaCode: '810000',
      regionalPinyin: 'XGTBXZQ',
      regionFullChineseName: 'XiangGangTeBieXingZhengQu',
      areaName: '香港特别行政区',
      upperAreaCode: '1',
      pinYin: 'XiangGang',
      areaType: 3,
    },
    {
      id: 50918,
      areaIdentifier: 'GD',
      chineseAbbreviation: '广东',
      areaCode: '440000',
      regionalPinyin: 'GDS',
      regionFullChineseName: 'GuangDongSheng',
      areaName: '广东省',
      upperAreaCode: '1',
      pinYin: 'GuangDong',
      areaType: 2,
    },
    {
      id: 51340,
      areaIdentifier: 'BJ',
      chineseAbbreviation: '北京',
      areaCode: '110000',
      regionalPinyin: 'BJS',
      regionFullChineseName: 'BeiJingShi',
      areaName: '北京',
      upperAreaCode: '1',
      pinYin: 'BeiJing',
      areaType: 2,
    },
    {
      id: 51702,
      areaIdentifier: 'JX',
      chineseAbbreviation: '江西',
      areaCode: '360000',
      regionalPinyin: 'JXS',
      regionFullChineseName: 'JiangXiSheng',
      areaName: '江西省',
      upperAreaCode: '1',
      pinYin: 'JiangXi',
      areaType: 2,
    },
    {
      id: 53517,
      areaIdentifier: 'XZ',
      chineseAbbreviation: '西藏',
      areaCode: '540000',
      regionalPinyin: 'XZZZQ',
      regionFullChineseName: 'XiZangZiZhiQu',
      areaName: '西藏自治区',
      upperAreaCode: '1',
      pinYin: 'XiZang',
      areaType: 2,
    },
    {
      id: 54292,
      areaIdentifier: 'GX',
      chineseAbbreviation: '广西',
      areaCode: '450000',
      regionalPinyin: 'GXZZZZQ',
      regionFullChineseName: 'GuangXiZhuangZuZiZhiQu',
      areaName: '广西壮族自治区',
      upperAreaCode: '1',
      pinYin: 'GuangXi',
      areaType: 2,
    },
    {
      id: 56169,
      areaIdentifier: 'SD',
      chineseAbbreviation: '山东',
      areaCode: '370000',
      regionalPinyin: 'SDS',
      regionFullChineseName: 'ShanDongSheng',
      areaName: '山东省',
      upperAreaCode: '1',
      pinYin: 'ShanDong',
      areaType: 2,
    },
    {
      id: 56669,
      areaIdentifier: 'SN',
      chineseAbbreviation: '陕西',
      areaCode: '610000',
      regionalPinyin: 'SXS',
      regionFullChineseName: 'ShaanXiSheng',
      areaName: '陕西省',
      upperAreaCode: '1',
      pinYin: 'ShaanXi',
      areaType: 2,
    },
    {
      id: 59995,
      areaIdentifier: 'HI',
      chineseAbbreviation: '海南',
      areaCode: '460000',
      regionalPinyin: 'HNS',
      regionFullChineseName: 'HaiNanSheng',
      areaName: '海南省',
      upperAreaCode: '1',
      pinYin: 'HaiNan',
      areaType: 2,
    },
    {
      id: 60680,
      areaIdentifier: 'HL',
      chineseAbbreviation: '黑龙江',
      areaCode: '230000',
      regionalPinyin: 'HLJS',
      regionFullChineseName: 'HeiLongJiangSheng',
      areaName: '黑龙江省',
      upperAreaCode: '1',
      pinYin: 'HeiLongJiang',
      areaType: 2,
    },
    {
      id: 63222,
      areaIdentifier: 'YN',
      chineseAbbreviation: '云南',
      areaCode: '530000',
      regionalPinyin: 'YNS',
      regionFullChineseName: 'YunNanSheng',
      areaName: '云南省',
      upperAreaCode: '1',
      pinYin: 'YunNan',
      areaType: 2,
    },
    {
      id: 63491,
      areaIdentifier: 'SH',
      chineseAbbreviation: '上海',
      areaCode: '310000',
      regionalPinyin: 'SHS',
      regionFullChineseName: 'ShangHaiShi',
      areaName: '上海',
      upperAreaCode: '1',
      pinYin: 'ShangHai',
      areaType: 2,
    },
    {
      id: 64373,
      areaIdentifier: 'GS',
      chineseAbbreviation: '甘肃',
      areaCode: '620000',
      regionalPinyin: 'GSS',
      regionFullChineseName: 'GanSuSheng',
      areaName: '甘肃省',
      upperAreaCode: '1',
      pinYin: 'GanSu',
      areaType: 2,
    },
    {
      id: 65291,
      areaIdentifier: 'JL',
      chineseAbbreviation: '吉林',
      areaCode: '220000',
      regionalPinyin: 'JLS',
      regionFullChineseName: 'JiLinSheng',
      areaName: '吉林省',
      upperAreaCode: '1',
      pinYin: 'JiLin',
      areaType: 2,
    },
    {
      id: 67410,
      areaIdentifier: 'MO',
      chineseAbbreviation: '澳门',
      areaCode: '820000',
      regionalPinyin: 'AMTBXZQ',
      regionFullChineseName: 'AoMenTeBieXingZhengQu',
      areaName: '澳门特别行政区',
      upperAreaCode: '1',
      pinYin: 'AoMen',
      areaType: 3,
    },
    {
      id: 70896,
      areaIdentifier: 'HN',
      chineseAbbreviation: '湖南',
      areaCode: '430000',
      regionalPinyin: 'HNS',
      regionFullChineseName: 'HuNanSheng',
      areaName: '湖南省',
      upperAreaCode: '1',
      pinYin: 'HuNan',
      areaType: 2,
    },
    {
      id: 71677,
      areaIdentifier: 'XJ',
      chineseAbbreviation: '新疆',
      areaCode: '650000',
      regionalPinyin: 'XJWWEZZQ',
      regionFullChineseName: 'XinJiangWeiWuErZiZhiQu',
      areaName: '新疆维吾尔自治区',
      upperAreaCode: '1',
      pinYin: 'XinJiang',
      areaType: 2,
    },
    {
      id: 72122,
      areaIdentifier: 'SC',
      chineseAbbreviation: '四川',
      areaCode: '510000',
      regionalPinyin: 'SCS',
      regionFullChineseName: 'SiChuanSheng',
      areaName: '四川省',
      upperAreaCode: '1',
      pinYin: 'SiChuan',
      areaType: 2,
    },
    {
      id: 72416,
      areaIdentifier: 'GZ',
      chineseAbbreviation: '贵州',
      areaCode: '520000',
      regionalPinyin: 'GZS',
      regionFullChineseName: 'GuiZhouSheng',
      areaName: '贵州省',
      upperAreaCode: '1',
      pinYin: 'GuiZhou',
      areaType: 2,
    },
    {
      id: 72426,
      areaIdentifier: 'TW',
      chineseAbbreviation: '台湾',
      areaCode: '710000',
      regionalPinyin: 'TWS',
      regionFullChineseName: 'TaiWanSheng',
      areaName: '台湾省',
      upperAreaCode: '1',
      pinYin: 'TaiWan',
      areaType: 2,
    },
    {
      id: 77571,
      areaIdentifier: 'CQ',
      chineseAbbreviation: '重庆',
      areaCode: '500000',
      regionalPinyin: 'CQS',
      regionFullChineseName: 'ChongQingShi',
      areaName: '重庆',
      upperAreaCode: '1',
      pinYin: 'ChongQing',
      areaType: 2,
    },
    {
      id: 78808,
      areaIdentifier: 'HE',
      chineseAbbreviation: '河北',
      areaCode: '130000',
      regionalPinyin: 'HBS',
      regionFullChineseName: 'HeBeiSheng',
      areaName: '河北省',
      upperAreaCode: '1',
      pinYin: 'HeBei',
      areaType: 2,
    },
    {
      id: 80126,
      areaIdentifier: 'ZJ',
      chineseAbbreviation: '浙江',
      areaCode: '330000',
      regionalPinyin: 'ZJS',
      regionFullChineseName: 'ZheJiangSheng',
      areaName: '浙江省',
      upperAreaCode: '1',
      pinYin: 'ZheJiang',
      areaType: 2,
    },
    {
      id: 81278,
      areaIdentifier: 'HA',
      chineseAbbreviation: '河南',
      areaCode: '410000',
      regionalPinyin: 'HNS',
      regionFullChineseName: 'HeNanSheng',
      areaName: '河南省',
      upperAreaCode: '1',
      pinYin: 'HeNan',
      areaType: 2,
    },
    {
      id: 85575,
      areaIdentifier: 'SX',
      chineseAbbreviation: '山西',
      areaCode: '140000',
      regionalPinyin: 'SXS',
      regionFullChineseName: 'ShanXiSheng',
      areaName: '山西省',
      upperAreaCode: '1',
      pinYin: 'ShanXi',
      areaType: 2,
    },
    {
      id: 86040,
      areaIdentifier: 'JS',
      chineseAbbreviation: '江苏',
      areaCode: '320000',
      regionalPinyin: 'JSS',
      regionFullChineseName: 'JiangSuSheng',
      areaName: '江苏省',
      upperAreaCode: '1',
      pinYin: 'JiangSu',
      areaType: 2,
    },
    {
      id: 86655,
      areaIdentifier: 'HB',
      chineseAbbreviation: '湖北',
      areaCode: '420000',
      regionalPinyin: 'HBS',
      regionFullChineseName: 'HuBeiSheng',
      areaName: '湖北省',
      upperAreaCode: '1',
      pinYin: 'HuBei',
      areaType: 2,
    },
    {
      id: 87909,
      areaIdentifier: 'AH',
      chineseAbbreviation: '安徽',
      areaCode: '340000',
      regionalPinyin: 'AHS',
      regionFullChineseName: 'AnHuiSheng',
      areaName: '安徽省',
      upperAreaCode: '1',
      pinYin: 'AnHui',
      areaType: 2,
    },
    {
      id: 91771,
      areaIdentifier: 'QH',
      chineseAbbreviation: '青海',
      areaCode: '630000',
      regionalPinyin: 'QHS',
      regionFullChineseName: 'QingHaiSheng',
      areaName: '青海省',
      upperAreaCode: '1',
      pinYin: 'QingHai',
      areaType: 2,
    },
    {
      id: 92941,
      areaIdentifier: 'FJ',
      chineseAbbreviation: '福建',
      areaCode: '350000',
      regionalPinyin: 'FJS',
      regionFullChineseName: 'FuJianSheng',
      areaName: '福建省',
      upperAreaCode: '1',
      pinYin: 'FuJian',
      areaType: 2,
    },
  ];
};
